// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCore.Dal.DataContext;

namespace WebApiCore.Dal.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20180713092647_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiCore.Dal.DataModel.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new { Id = 1, Type = "user" },
                        new { Id = 2, Type = "admin" }
                    );
                });

            modelBuilder.Entity("WebApiCore.Dal.DataModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, Name = "Anna", RoleId = 1 },
                        new { Id = 2, Name = "Petr", RoleId = 2 },
                        new { Id = 3, Name = "Ira", RoleId = 1 },
                        new { Id = 4, Name = "Oleg", RoleId = 1 },
                        new { Id = 5, Name = "Karina", RoleId = 1 }
                    );
                });

            modelBuilder.Entity("WebApiCore.Dal.DataModel.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId");

                    b.Property<string>("UserText");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserData");

                    b.HasData(
                        new { Id = 1, UserId = 1, UserText = "My name is Anna. My role is user." },
                        new { Id = 2, UserId = 2, UserText = "My name is Petr. My role is admin." },
                        new { Id = 3, UserId = 3, UserText = "My name is Ira. My role is user." },
                        new { Id = 4, UserId = 4, UserText = "My name is Oleg. My role is user." },
                        new { Id = 5, UserId = 5, UserText = "My name is Karina. My role is user." }
                    );
                });

            modelBuilder.Entity("WebApiCore.Dal.DataModel.User", b =>
                {
                    b.HasOne("WebApiCore.Dal.DataModel.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiCore.Dal.DataModel.UserData", b =>
                {
                    b.HasOne("WebApiCore.Dal.DataModel.User", "User")
                        .WithMany("UserData")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
